### ISSUE TITLE
"unsupported Ruby engine" with jruby 1.6.4 in 1.9 mode

### ISSUE THREAD

**Issue by tomdz** [headius/ruby-atomic#10]
When using atomic (0.0.9 java as per `gem list`) with jruby 1.6.4 in 1.9 mode I get this warning:

`unsupported Ruby engine, using less-efficient Atomic impl`

**Comment by headius** [comment]
I can't reproduce this on JRuby 1.6.6, so I think it's probably fine now. Reopen if you're still having trouble on a recent JRuby.

**Comment by tomdz** [comment]
You're right, works like a charm with 1.6.6, thx !
