### ISSUE TITLE
x64-minw32 bug

### ISSUE THREAD

**Issue by conrad-vanl** [headius/ruby-atomic#13]
Cross-posting: https://github.com/rails/rails/issues/9506

Atomic won't install on Ruby 2.0 x64-mingw32 on windows.

As @betam4x noticed, there is a bug in ruby-atomic/ext/extconf.rb:

> ``` Ruby
> when /mswin32|mingw/
>     $CFLAGS += " -march=i686"
> end
> ```
> 
> it's not checking for x64-mingw32, and is using the wrong architecture as a result. I would report this to the atomic gem author, but it looks like the gem hasn't been updated in a long time.

**Comment by luislavena** [comment]
Hello,

This was reported to RubyInstaller group too, so chiming in :wink: 
- `mswin32` platform is not compatible with GCC compilation flags, so using this with Visual C will cause compilation failures.
- Forcing architecture based on the platform seems to be missing the issue, and I think such flag should be removed to expose the real bug (and we can all work on fix it)

RubyInstaller already provides binaries for Ruby 2.0.0 x64 and DevKit to easily test this out.

@headius let me know if you need something else to fix this.

Thank you.

**Comment by betam4x** [comment]
FYI I removed that entire code block as a test.  Compiles fine with the 2012 devkit.  I was able to install rails.  Still breaks on the older devkit (for 1.9.3) when compiling (if you remove that block) so it looks like he was working around a bug that no longer exists.

**Comment by luislavena** [comment]
@betam4x can you provide the compilation output where the error happens?

Since 1.9.3 DevKit is GCC 4.5.2, perhaps additional checks are required in the code.

**Comment by betam4x** [comment]
generating atomic_reference-i386-mingw32.def
compiling atomic_reference.c
linking shared-object atomic_reference.so
atomic_reference.o: In function `ir_compare_and_set':
C:\Ruby193\lib\ruby\gems\1.9.1\gems\atomic-1.0.0\ext/atomic_reference.c:38: undefined reference to`__sync_bool_compare_and_swap_4'
collect2: ld returned 1 exit status
make: **\* [atomic_reference.so] Error 1

Gem files will remain installed in C:/Ruby193/lib/ruby/gems/1.9.1/gems/atomic-1.0.0 for inspection.
Results logged to C:/Ruby193/lib/ruby/gems/1.9.1/gems/atomic-1.0.0/ext/gem_make.out

**Comment by luislavena** [comment]
So is coming from here:

https://github.com/headius/ruby-atomic/blob/master/ext/atomic_reference.c#L37-L40

Which confirms the missing GNU GCC functions for that particular version of GCC from mingw.org

I think checks for the GNU atomic functions needs to be added to extconf so this undefined reference can be avoided.

I'll try to look into this tonight at home.

**Comment by zimbatm** [comment]
I think that we also need to add a fallback with a lock for it to work.

**Comment by zimbatm** [comment]
Or integrate an external library but the complexity of something like https://github.com/ivmai/libatomic_ops makes me shudder.

**Comment by zimbatm** [comment]
Can someone with a Windows box test my branch ?

**Comment by Energy0124** [comment]
Hello,

I faced the exact problem when I am trying to install Atomic.
I changed  

``` ruby
    $CFLAGS += " -march=i686"
```

to

``` ruby
    $CFLAGS += " -march=native"
```

and installed successfully. 
Is it possible to fix the problem like this?

Sorry that I actually know very little about C. If this is wrong, you can just ignore me.
Thank you.

**Comment by ghost** [comment]
I am on windows, I am getting the same error following error - 

``` ruby
make
generating atomic_reference-x64-mingw32.def
compiling atomic_reference.c
atomic_reference.c:1:0: error: CPU you selected does not support x86-64 instruction set
make: *** [atomic_reference.o] Error 1
```

**Comment by ghost** [comment]
I got the latest source did the change as recommended by Energy0124

``` ruby
$CFLAGS += " -march=native"
```

and it works on windows. 

Thanks

**Comment by headius** [comment]
So is there a PR in here somewhere? Sorry I didn't see the issue until now, but I'm unclear what needs to be changed.

**Comment by headius** [comment]
I believe this will be fixed by #20 and #15 which are both merged. I will release 1.1.7 shortly which adds #20 (#15 was already in 1.1.6).

If there's other issues, like getting this to compile with both VC++ and mingw, please open another issue/PR.

**Comment by vision2910** [comment]
The solution suggested by Energy0124 and tried by lazyspark, is already in place in my extconf.rb
But still getting same error. I am using ruby 1.9.3p429. 

Any other solution?

**Comment by headius** [comment]
@vision2910 Can you file a new issue and confirm you're installing latest ruby-atomic? This thread is closed.
