### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by replaid** [headius/ruby-atomic#14]
Dear team,

Master fails to build for MRI 1.9.2-p0 on my MacBook Pro.

~/dir ▶cd ruby-atomic/
~/dir/ruby-atomic ▶rake
Loaded suite /Users/rep/.rvm/gems/ruby-1.9.2-p0/gems/rake-10.0.4/lib/rake/rake_test_loader
Started
.......
Finished in 0.032805 seconds.

7 tests, 11 assertions, 0 failures, 0 errors, 0 skips

Test run options: --seed 65254
~/dir/ruby-atomic ▶gem build atomic.gemspec 
WARNING:  no rubyforge_project specified
WARNING:  description and summary are identical
  Successfully built RubyGem
  Name: atomic
  Version: 1.0.2
  File: atomic-1.0.2.gem
~/dir/ruby-atomic ▶gem install atomic-1.0.2.gem 
Building native extensions.  This could take a while...
ERROR:  Error installing atomic-1.0.2.gem:
    ERROR: Failed to build gem native extension.

/Users/rep/.rvm/rubies/ruby-1.9.2-p0/bin/ruby extconf.rb
creating Makefile

make
gcc -I. -I/Users/rep/.rvm/rubies/ruby-1.9.2-p0/include/ruby-1.9.1/i386-darwin10.4.0 -I/Users/rep/.rvm/rubies/ruby-1.9.2-p0/include/ruby-1.9.1/ruby/backward -I/Users/rep/.rvm/rubies/ruby-1.9.2-p0/include/ruby-1.9.1 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE   -fno-common -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wshorten-64-to-32 -Wno-long-long  -fno-common -pipe  -o atomic_reference.o -c atomic_reference.c
In file included from /Users/rep/.rvm/rubies/ruby-1.9.2-p0/include/ruby-1.9.1/ruby.h:32,
                 from atomic_reference.c:13:
/Users/rep/.rvm/rubies/ruby-1.9.2-p0/include/ruby-1.9.1/ruby/ruby.h:108: error: size of array ‘ruby_check_sizeof_long’ is negative
/Users/rep/.rvm/rubies/ruby-1.9.2-p0/include/ruby-1.9.1/ruby/ruby.h:112: error: size of array ‘ruby_check_sizeof_voidp’ is negative
In file included from /Users/rep/.rvm/rubies/ruby-1.9.2-p0/include/ruby-1.9.1/ruby/intern.h:29,
                 from /Users/rep/.rvm/rubies/ruby-1.9.2-p0/include/ruby-1.9.1/ruby/ruby.h:1327,
                 from /Users/rep/.rvm/rubies/ruby-1.9.2-p0/include/ruby-1.9.1/ruby.h:32,
                 from atomic_reference.c:13:
/Users/rep/.rvm/rubies/ruby-1.9.2-p0/include/ruby-1.9.1/ruby/st.h:69: error: size of array ‘st_check_for_sizeof_st_index_t’ is negative
make: **\* [atomic_reference.o] Error 1

Gem files will remain installed in /Users/myusername/.rvm/gems/ruby-1.9.2-p0/gems/atomic-1.0.2 for inspection.
Results logged to /Users/rep/.rvm/gems/ruby-1.9.2-p0/gems/atomic-1.0.2/ext/gem_make.out
~/dir/ruby-atomic ▶uname -a
Darwin mycomputername.local 11.4.2 Darwin Kernel Version 11.4.2: Thu Aug 23 16:25:48 PDT 2012; root:xnu-1699.32.7~1/RELEASE_X86_64 x86_64

**Comment by zimbatm** [comment]
Can you give use the version of OSX, xcode and GCC that you have ?

**Comment by replaid** [comment]
Mac OS X 10.7.5
Xcode 4.1
gcc 4.2.1

~ ▶/Developer/usr/bin/xcodebuild -version
Xcode 4.1
Build version 4B110
~ ▶gcc --version
i686-apple-darwin11-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.15.00)
Copyright (C) 2007 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by zimbatm** [comment]
It might be an arch compatibility issue, esp. if you upgraded OSX since you last installed ruby. Can you try and re-install ruby ?

**Comment by zimbatm** [comment]
Just some reference I found: http://jtigger-learning.wikidot.com/gem-install-fails-on-building-native-extensions

**Comment by replaid** [comment]
Thanks for your help. Spot on—I switched rvm to a ruby built as 64-bit and whaddaya know, it works fine. Apologies for the distraction.
