### ISSUE TITLE
atomic-1.1.6   Trojan.Menti reported during install on Windows 7 

### ISSUE THREAD

**Issue by DHB** [headius/ruby-atomic#18]
When updating to atomic 1.1.6 Malwarebytes (Anti-malware)  reports:

``` shell
2013/04/07 00:30:13 +0200   DHB-PC  development DETECTION   h:\ruby200_p0\lib\ruby\gems\2.0.0\gems\atomic-1.1.6\ext\conftest.exe    Trojan.Menti    QUARANTINE
```

**Comment by headius** [comment]
Strange...that file shouldn't exist in the repo or the gem. Where would it
have come from?
- Charlie (mobile)

**Comment by headius** [comment]
OK...that probably comes from a test compile during ext building, but there's just source in the gem. False positive perhaps?

**Comment by DHB** [comment]
It's really strange.  I now believe it's got nothing to do with atomic. 

conftest.exe is invoked from gcc during compile. I never saw the issue before with other gems though. 

It made me super nervous, Trojan.Menti is known to be extremely aggressiv.  I shouldn't have posted it here without more investigating first, sorry. 

I believe you can close the issue. Thx for your quick response.

**Comment by headius** [comment]
Thanks for following up.
