### ISSUE TITLE
Drop the changelog from description

### ISSUE THREAD

**Issue by voxik** [headius/ruby-atomic#22]
The description breaks the RubyGems.org page layout [1]. Could you please get rid of it? Not sure if the changelog should go into description anyway. Thanks.

[1] http://rubygems.org/gems/atomic

**Comment by headius** [comment]
RubyGems.org breaks the RubyGems.org page layout :-) I had been leaving my content there to force them to consider fixing it, but they don't appear to be interested.

I'll do something to remove it...it's just disappointing that you can't put a useful description into the gem page.

**Comment by voxik** [comment]
Heh, nice ... then please revert the commit ;) I support your case!

**Comment by headius** [comment]
Nah...it's a done deal. I'm not in the mood to keep fighting it, and you're
not the only one to point out the broken RG page. :-)
