### ISSUE TITLE
gem install atomic -v '1.1.14' fires anti-virus warning

### ISSUE THREAD

**Issue by arjunmenon** [headius/ruby-atomic#34]
@headius @zimbatm @mental 
i am getting this error with an anti-virus warning Win32:Evo-gen [susp]

``` ruby
>gem install atomic -v '1.1.14'
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing atomic:
        ERROR: Failed to build gem native extension.

    C:/RailsInstaller/Ruby1.9.3/bin/ruby.exe extconf.rb
creating Makefile

make
generating atomic_reference-i386-mingw32.def
compiling atomic_reference.c
atomic_reference.c: In function 'ir_compare_and_set':
atomic_reference.c:75:2: error: #error No CAS operation available for this platf
orm
make: *** [atomic_reference.o] Error 1


Gem files will remain installed in C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9
.1/gems/atomic-1.1.14 for inspection.
Results logged to C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/atomic-1.
1.14/ext/gem_make.out
```

this was in the anti-virus log file

```
C:\RailsInstaller\Ruby1.9.3\lib\ruby\gems\1.9.1\gems\atomic-1.1.14\ext\conftest.exe [L] Win32:Evo-gen [Susp] (0)
```

**Comment by zimbatm** [comment]
Most likely your anti-virus is wrong and you would have to file a complaint with them for a false positive.

Just to be sure, check the content of atomic_reference.c against https://github.com/headius/ruby-atomic/blob/1.1.14/ext/atomic_reference.c and see if there is any difference.

**Comment by arjunmenon** [comment]
yup no change in content. i did what u said and to make it work excluded the conftest.exe from scan. 
i m not sure of precise functioning of anti virus, but i hope it does not stop checking any thing vaguely similar coz reporting of false positive. 

thanks a lot. :+1:

**Comment by headius** [comment]
I'm going to mark this invalid, since there's nothing shipped in the gem that should trigger a virus warning. It's likely (as @zimbatm stated) that the built binaries just happen to match a virus marker in your detector.
