### ISSUE TITLE
broken on Windows with MRI (since 1.1.14)

### ISSUE THREAD

**Issue by kares** [headius/ruby-atomic#40]
likely due : https://github.com/headius/ruby-atomic/commit/07d114594e20ac35444a3791834994ebe2914192 @orderthruchaos any chance you'll fix it ?

![gem_install_atomic](https://f.cloud.github.com/assets/45967/2324770/0b5ebee0-a3cd-11e3-948e-f83811a48773.jpg)

**Comment by orderthruchaos** [comment]
Curious.  I don't have a ruby that old lying around.  Could you run this for me, and post the results?

``` sh
ruby -rmkmf -e 'p CONFIG["GCC"] ; p CONFIG["CC"]'
```

**Comment by kares** [comment]
```
C:\Users\kares>ruby -rmkmf -e 'p CONFIG["GCC"] ; p CONFIG["CC"]'
nil
"gcc"
```

**Comment by orderthruchaos** [comment]
That's the most likely culprit.  I'll try to update extconf.rb to detect gcc in CONFIG["CC"].  Sorry, should have thought of that.

**Comment by orderthruchaos** [comment]
In the meantime, you may wish to try:

``` sh
CPPFLAGS='-DHAVE_GCC_CAS' ruby -S gem install atomic
```

**Comment by kares** [comment]
Thanks Brett, I just want the gem to install on MRI/Windows as well (as it's **thread_safe**'s dependency),  using 1.1.13 is fine with me for now ...
