### ISSUE TITLE
broken on Mac OS X Mavericks

### ISSUE THREAD

**Issue by bobbyduhbrain** [headius/ruby-atomic#42]
I received the following error:

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb 
```

checking for libkern/OSAtomic.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling atomic_reference.c
atomic_reference.c:57:59: warning: incompatible pointer types passing 'void *_' to parameter of type 'volatile int64_t *' (aka 'volatile long long *') [-Wincompatible-pointer-types]
    if (OSAtomicCompareAndSwap64(expect_value, new_value, &DATA_PTR(self))) {
                                                          ^~~~~~~~~~~~~~~
/usr/include/libkern/OSAtomic.h:507:93: note: passing argument to parameter '__theValue' here
bool    OSAtomicCompareAndSwap64( int64_t __oldValue, int64_t __newValue, volatile int64_t *__theValue );
                                                                                            ^
1 warning generated.
linking shared-object atomic_reference.bundle
clang: error: unknown argument: '-multiply_definedsuppress' [-Wunused-command-line-argument-hard-error-in-future]
clang: note: this will be a hard error (cannot be downgraded to a warning) in the future
make: *_\* [atomic_reference.bundle] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/Mike/.bundler/tmp/42623/gems/atomic-1.1.15 for inspection.
Results logged to /Users/Mike/.bundler/tmp/42623/extensions/universal-darwin-13/2.0.0/atomic-1.1.15/gem_make.out

I am running the latest version of OSX Mavericks with the latest Xcode and the Command Line Tools installed.

**Comment by bobbyduhbrain** [comment]
Managed to fix this by reinstalling ruby using rvm.  Now Atomic seems to install without a problem.  Not sure exactly what was going on but I'll leave this open so someone has a chance to look at it.

**Comment by jnozsc** [comment]
I met this issue yesterday,
I think the solution should be this one http://stackoverflow.com/q/22352838

It seems the build-in Ruby in Mac OS X is not up-to-date.

**Comment by bobbyduhbrain** [comment]
Good find.  I appreciate the link!  I wish I had found that answer sooner as I tried everything under the sun before a clean reinstall of Ruby.
