### ISSUE TITLE
Instalation fails on Ubuntu 13.10

### ISSUE THREAD

**Issue by zalapeach** [headius/ruby-atomic#46]
Hello guys, actually I get this problem when I try to install this gem on Ubuntu 13.10

bundle install
Fetching gem metadata from https://rubygems.org/..........
Fetching additional metadata from https://rubygems.org/..
Using rake 10.1.1
Using i18n 0.6.9
Using minitest 4.7.5
Using multi_json 1.8.4

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

```
/home/zala/.rvm/rubies/ruby-2.1.1/bin/ruby extconf.rb 
```

/home/zala/.rvm/rubies/ruby-2.1.1/bin/ruby: invalid option -z  (-h will show valid options) (RuntimeError)

extconf failed, exit code 1

Gem files will remain installed in /home/zala/.rvm/gems/ruby-2.1.1@  zip_areas/gems/atomic-1.1.14 for inspection.
Results logged to /home/zala/.rvm/gems/ruby-2.1.1@  zip_areas/extensions/x86_64-linux/2.1.0/atomic-1.1.14/gem_make.out
An error occurred while installing atomic (1.1.14), and Bundler cannot continue.
Make sure that `gem install atomic -v '1.1.14'` succeeds before bundling.

How can I fix this?

**Comment by digitalfrost** [comment]
Can this issue be closed?
Issue dates from 2014 ? 
Ubuntu 13.10 is not an LTS release
