### ISSUE TITLE
Version 0.0.8?

### ISSUE THREAD

**Issue by AlekSi** [headius/ruby-atomic#9]
Right now https://rubygems.org/gems/atomic shows 0.0.8 as current version, but latest commit 0f34f2553175794b9c7d371689fb2e3e65c6d5d0 shows version bump to 0.0.7. So where is a source for 0.0.8?

**Comment by headius** [comment]
Oops, I had unpushed commits locally. Guess I got a little excited about the release and never pushed.

The commits and a tag for 0.0.8 are in now. Thanks for pointing it out!
